/**
 * ABox 一盒 · 图标码位表（**唯一真源 · 两端共用**）
 *
 * 字形来源：Tabler Icons 3.47.0（MIT）· 官方 woff2 子集化，仅保留本表 82 个码位
 * 子集实测：原始 502,600 字节 → 12,188 字节（**2.4%**）；82 码位全在、无多余、83 字形（含 .notdef）
 *
 * ## 为什么放在共享包
 *
 * 「两端共用一套图标」不是口号：字形文件**同一份**、码位表**同一份**。
 * 两端各写一份映射表 = 两份表述，改一处必漏一处。
 *
 * ## 为什么是 iconfont 而不是 SVG
 *
 * 小程序**不支持** `<use href>` 引用外部 svg，内联 `<svg>` 与 `<image>` 在小程序内表现不可靠。
 * 故两端共用的唯一可执行形态是 **iconfont（base64 内嵌 woff2）**：
 * 端上用 `<text class="abi">`、后台用 `<i class="abi">`，引用的是同一份字形。
 *
 * ## 尺寸：功能三档 + 装饰四档（**分类登记，不得混用**）
 *
 * 功能图标：16 / 20 / 24（逻辑像素）—— 行内 / 按钮内 / 独立。端上 rpx（×2：32 / 40 / 48rpx）。
 * 装饰插图：14 / 28 / 34 / 40（逻辑像素）—— 空状态 / 占位 / hero 视觉主体。端上 28 / 56 / 68 / 80rpx。
 * 两族**各自锁档**；把装饰尺寸混进功能族，「尺寸锁三档」这条规则就名存实亡。
 *
 * ⚠️ 本文件由 `_tmp/icons/gen-assets.py` 生成，**不要手改**；改映射请改生成器再重跑。
 */

export const ABOX_ICON_LIB = 'tabler-icons@3.47.0';
export const ABOX_ICON_COUNT = 82;

/** 语义名 → Unicode 码位（前端不直接用它，用组件 `<ab-icon name>`） */
export const ABOX_ICON_CODEPOINTS = {
  alert: 0xea05,
  back: 0xea19,
  bell: 0xea35,
  box: 0xea45,
  building: 0xea4f,
  calendar: 0xea53,
  camera: 0xea54,
  cash: 0xea55,
  chart: 0xea59,
  check: 0xea5e,
  checklist: 0xf074,
  chev: 0xea61,
  clock: 0xea70,
  close: 0xeb55,
  coins: 0xf65d,
  cook: 0xf21d,
  copy: 0xea7a,
  crown: 0xed12,
  cup: 0xef28,
  dashboard: 0xf02c,
  discount: 0xebbd,
  download: 0xea96,
  edit: 0xeb04,
  egg: 0xeb8a,
  eye: 0xea9a,
  filter: 0xeaa5,
  fish: 0xef2b,
  flame: 0xec2c,
  fragile: 0xee17,
  gear: 0xeb20,
  gift: 0xeb68,
  history: 0xebea,
  home: 0xeac1,
  image: 0xeb0a,
  info: 0xeac5,
  invoice: 0xeb67,
  key: 0xeac7,
  layout: 0xedba,
  link: 0xeade,
  list: 0xeb6b,
  lock: 0xeae2,
  logout: 0xeba8,
  meat: 0xef12,
  medal: 0xec78,
  menu: 0xec42,
  message: 0xeaed,
  'ok-circle': 0xea67,
  package: 0xeaff,
  pause: 0xed45,
  phone: 0xeb09,
  pin: 0xeae8,
  play: 0xed46,
  plus: 0xeb0b,
  print: 0xeb0e,
  qr: 0xeb11,
  receipt: 0xedfd,
  refresh: 0xeb13,
  refund: 0xedfc,
  rice: 0xfd90,
  salad: 0xf50a,
  scan: 0xebc8,
  search: 0xeb1c,
  send: 0xeb1e,
  share: 0xeb21,
  shield: 0xeb24,
  sort: 0xeb5a,
  soup: 0xef2e,
  split: 0xeab2,
  star: 0xeb2e,
  store: 0xea4e,
  tag: 0x10096,
  temp: 0xeb38,
  template: 0xeb39,
  trash: 0xeb41,
  truck: 0xec4b,
  upload: 0xeb47,
  users: 0xebf2,
  veg: 0xf21c,
  wallet: 0xeb75,
  'warn-tri': 0xea06,
  withdraw: 0xee25,
  'x-circle': 0xea6a,
} as const;

export type AboxIconName = keyof typeof ABOX_ICON_CODEPOINTS;

/** 全部语义名（供自检遍历） */
export const ABOX_ICON_NAMES = [
  'alert',
  'back',
  'bell',
  'box',
  'building',
  'calendar',
  'camera',
  'cash',
  'chart',
  'check',
  'checklist',
  'chev',
  'clock',
  'close',
  'coins',
  'cook',
  'copy',
  'crown',
  'cup',
  'dashboard',
  'discount',
  'download',
  'edit',
  'egg',
  'eye',
  'filter',
  'fish',
  'flame',
  'fragile',
  'gear',
  'gift',
  'history',
  'home',
  'image',
  'info',
  'invoice',
  'key',
  'layout',
  'link',
  'list',
  'lock',
  'logout',
  'meat',
  'medal',
  'menu',
  'message',
  'ok-circle',
  'package',
  'pause',
  'phone',
  'pin',
  'play',
  'plus',
  'print',
  'qr',
  'receipt',
  'refresh',
  'refund',
  'rice',
  'salad',
  'scan',
  'search',
  'send',
  'share',
  'shield',
  'sort',
  'soup',
  'split',
  'star',
  'store',
  'tag',
  'temp',
  'template',
  'trash',
  'truck',
  'upload',
  'users',
  'veg',
  'wallet',
  'warn-tri',
  'withdraw',
  'x-circle',
] as const;

/** 语义名 → Tabler 原图标名（便于溯源；`fragile`/`rice` 无同名，见生成器注） */
export const ABOX_ICON_SOURCES: Record<AboxIconName, string> = {
  alert: 'alert-circle',
  back: 'arrow-left',
  bell: 'bell',
  box: 'box',
  building: 'building',
  calendar: 'calendar',
  camera: 'camera',
  cash: 'cash',
  chart: 'chart-bar',
  check: 'check',
  checklist: 'checklist',
  chev: 'chevron-right',
  clock: 'clock',
  close: 'x',
  coins: 'coins',
  cook: 'chef-hat',
  copy: 'copy',
  crown: 'crown',
  cup: 'cup',
  dashboard: 'layout-dashboard',
  discount: 'discount',
  download: 'download',
  edit: 'pencil',
  egg: 'egg',
  eye: 'eye',
  filter: 'filter',
  fish: 'fish',
  flame: 'flame',
  fragile: 'box-multiple',
  gear: 'settings',
  gift: 'gift',
  history: 'history',
  home: 'home',
  image: 'photo',
  info: 'info-circle',
  invoice: 'file-invoice',
  key: 'key',
  layout: 'layout-grid',
  link: 'link',
  list: 'list',
  lock: 'lock',
  logout: 'logout',
  meat: 'meat',
  medal: 'medal',
  menu: 'menu-2',
  message: 'message-circle',
  'ok-circle': 'circle-check',
  package: 'package',
  pause: 'player-pause',
  phone: 'phone',
  pin: 'map-pin',
  play: 'player-play',
  plus: 'plus',
  print: 'printer',
  qr: 'qrcode',
  receipt: 'receipt',
  refresh: 'refresh',
  refund: 'receipt-refund',
  rice: 'bowl-chopsticks',
  salad: 'salad',
  scan: 'scan',
  search: 'search',
  send: 'send',
  share: 'share',
  shield: 'shield',
  sort: 'arrows-sort',
  soup: 'soup',
  split: 'git-branch',
  star: 'star',
  store: 'building-store',
  tag: 'tag',
  temp: 'temperature',
  template: 'template',
  trash: 'trash',
  truck: 'truck-delivery',
  upload: 'upload',
  users: 'users',
  veg: 'carrot',
  wallet: 'wallet',
  'warn-tri': 'alert-triangle',
  withdraw: 'cash-banknote',
  'x-circle': 'circle-x',
};

/** 语义名 → 字符（端上**全部图标位的唯一承载方式**）
 *
 * ## 为什么端上所有图标位都走字符、不走组件
 *
 * 微信官方文档（text 组件 · Bug & Tip）原文：
 *   `tip`: text 组件内**只支持 text 嵌套**。
 * 即 `<text>` **不能内嵌自定义组件** —— 而端上 63/78 个图标位是「图标 + 中文」
 * 混排在同一 `<text>` 里（卡片标题 / 菜单行 / 提示条 / 按钮文案）。这些位置若写
 * `<ab-icon>`，组件节点会被渲染层**静默丢弃**（不报错、不警告、位置空着）。
 *
 * ⇒ 唯一能同时覆盖「混排位」与「独立位」的写法是**统一的 class 约定**：
 *
 *   <text class="abi abi-16">{{ I.chart }}</text>       功能图标（行内）
 *   <text class="abi abi-deco-40">{{ I.rice }}</text>    装饰插图
 *
 * 嵌套 `<text>` 官方支持（同文档示例：`<text> foo <text>bar</text> </text>`），
 * 且嵌套层上的 `font-size` 是**直接声明**，能盖住父级 `<text>` 继承来的字号 ——
 * 这正是「三档锁」在混排语境下得以成立的前提。
 *
 * 本表由码位表派生，不复制第二份数字。
 */
export const ABOX_ICON_CHARS: Record<AboxIconName, string> = {
  alert: String.fromCodePoint(ABOX_ICON_CODEPOINTS.alert),
  back: String.fromCodePoint(ABOX_ICON_CODEPOINTS.back),
  bell: String.fromCodePoint(ABOX_ICON_CODEPOINTS.bell),
  box: String.fromCodePoint(ABOX_ICON_CODEPOINTS.box),
  building: String.fromCodePoint(ABOX_ICON_CODEPOINTS.building),
  calendar: String.fromCodePoint(ABOX_ICON_CODEPOINTS.calendar),
  camera: String.fromCodePoint(ABOX_ICON_CODEPOINTS.camera),
  cash: String.fromCodePoint(ABOX_ICON_CODEPOINTS.cash),
  chart: String.fromCodePoint(ABOX_ICON_CODEPOINTS.chart),
  check: String.fromCodePoint(ABOX_ICON_CODEPOINTS.check),
  checklist: String.fromCodePoint(ABOX_ICON_CODEPOINTS.checklist),
  chev: String.fromCodePoint(ABOX_ICON_CODEPOINTS.chev),
  clock: String.fromCodePoint(ABOX_ICON_CODEPOINTS.clock),
  close: String.fromCodePoint(ABOX_ICON_CODEPOINTS.close),
  coins: String.fromCodePoint(ABOX_ICON_CODEPOINTS.coins),
  cook: String.fromCodePoint(ABOX_ICON_CODEPOINTS.cook),
  copy: String.fromCodePoint(ABOX_ICON_CODEPOINTS.copy),
  crown: String.fromCodePoint(ABOX_ICON_CODEPOINTS.crown),
  cup: String.fromCodePoint(ABOX_ICON_CODEPOINTS.cup),
  dashboard: String.fromCodePoint(ABOX_ICON_CODEPOINTS.dashboard),
  discount: String.fromCodePoint(ABOX_ICON_CODEPOINTS.discount),
  download: String.fromCodePoint(ABOX_ICON_CODEPOINTS.download),
  edit: String.fromCodePoint(ABOX_ICON_CODEPOINTS.edit),
  egg: String.fromCodePoint(ABOX_ICON_CODEPOINTS.egg),
  eye: String.fromCodePoint(ABOX_ICON_CODEPOINTS.eye),
  filter: String.fromCodePoint(ABOX_ICON_CODEPOINTS.filter),
  fish: String.fromCodePoint(ABOX_ICON_CODEPOINTS.fish),
  flame: String.fromCodePoint(ABOX_ICON_CODEPOINTS.flame),
  fragile: String.fromCodePoint(ABOX_ICON_CODEPOINTS.fragile),
  gear: String.fromCodePoint(ABOX_ICON_CODEPOINTS.gear),
  gift: String.fromCodePoint(ABOX_ICON_CODEPOINTS.gift),
  history: String.fromCodePoint(ABOX_ICON_CODEPOINTS.history),
  home: String.fromCodePoint(ABOX_ICON_CODEPOINTS.home),
  image: String.fromCodePoint(ABOX_ICON_CODEPOINTS.image),
  info: String.fromCodePoint(ABOX_ICON_CODEPOINTS.info),
  invoice: String.fromCodePoint(ABOX_ICON_CODEPOINTS.invoice),
  key: String.fromCodePoint(ABOX_ICON_CODEPOINTS.key),
  layout: String.fromCodePoint(ABOX_ICON_CODEPOINTS.layout),
  link: String.fromCodePoint(ABOX_ICON_CODEPOINTS.link),
  list: String.fromCodePoint(ABOX_ICON_CODEPOINTS.list),
  lock: String.fromCodePoint(ABOX_ICON_CODEPOINTS.lock),
  logout: String.fromCodePoint(ABOX_ICON_CODEPOINTS.logout),
  meat: String.fromCodePoint(ABOX_ICON_CODEPOINTS.meat),
  medal: String.fromCodePoint(ABOX_ICON_CODEPOINTS.medal),
  menu: String.fromCodePoint(ABOX_ICON_CODEPOINTS.menu),
  message: String.fromCodePoint(ABOX_ICON_CODEPOINTS.message),
  'ok-circle': String.fromCodePoint(ABOX_ICON_CODEPOINTS['ok-circle']),
  package: String.fromCodePoint(ABOX_ICON_CODEPOINTS.package),
  pause: String.fromCodePoint(ABOX_ICON_CODEPOINTS.pause),
  phone: String.fromCodePoint(ABOX_ICON_CODEPOINTS.phone),
  pin: String.fromCodePoint(ABOX_ICON_CODEPOINTS.pin),
  play: String.fromCodePoint(ABOX_ICON_CODEPOINTS.play),
  plus: String.fromCodePoint(ABOX_ICON_CODEPOINTS.plus),
  print: String.fromCodePoint(ABOX_ICON_CODEPOINTS.print),
  qr: String.fromCodePoint(ABOX_ICON_CODEPOINTS.qr),
  receipt: String.fromCodePoint(ABOX_ICON_CODEPOINTS.receipt),
  refresh: String.fromCodePoint(ABOX_ICON_CODEPOINTS.refresh),
  refund: String.fromCodePoint(ABOX_ICON_CODEPOINTS.refund),
  rice: String.fromCodePoint(ABOX_ICON_CODEPOINTS.rice),
  salad: String.fromCodePoint(ABOX_ICON_CODEPOINTS.salad),
  scan: String.fromCodePoint(ABOX_ICON_CODEPOINTS.scan),
  search: String.fromCodePoint(ABOX_ICON_CODEPOINTS.search),
  send: String.fromCodePoint(ABOX_ICON_CODEPOINTS.send),
  share: String.fromCodePoint(ABOX_ICON_CODEPOINTS.share),
  shield: String.fromCodePoint(ABOX_ICON_CODEPOINTS.shield),
  sort: String.fromCodePoint(ABOX_ICON_CODEPOINTS.sort),
  soup: String.fromCodePoint(ABOX_ICON_CODEPOINTS.soup),
  split: String.fromCodePoint(ABOX_ICON_CODEPOINTS.split),
  star: String.fromCodePoint(ABOX_ICON_CODEPOINTS.star),
  store: String.fromCodePoint(ABOX_ICON_CODEPOINTS.store),
  tag: String.fromCodePoint(ABOX_ICON_CODEPOINTS.tag),
  temp: String.fromCodePoint(ABOX_ICON_CODEPOINTS.temp),
  template: String.fromCodePoint(ABOX_ICON_CODEPOINTS.template),
  trash: String.fromCodePoint(ABOX_ICON_CODEPOINTS.trash),
  truck: String.fromCodePoint(ABOX_ICON_CODEPOINTS.truck),
  upload: String.fromCodePoint(ABOX_ICON_CODEPOINTS.upload),
  users: String.fromCodePoint(ABOX_ICON_CODEPOINTS.users),
  veg: String.fromCodePoint(ABOX_ICON_CODEPOINTS.veg),
  wallet: String.fromCodePoint(ABOX_ICON_CODEPOINTS.wallet),
  'warn-tri': String.fromCodePoint(ABOX_ICON_CODEPOINTS['warn-tri']),
  withdraw: String.fromCodePoint(ABOX_ICON_CODEPOINTS.withdraw),
  'x-circle': String.fromCodePoint(ABOX_ICON_CODEPOINTS['x-circle']),
};

/** 码位 → 字符（端上 <text> 用） */
export function iconChar(name: AboxIconName): string {
  return String.fromCodePoint(ABOX_ICON_CODEPOINTS[name]);
}
